language: node_js

node_js:
  - "8"

stages:
- test
- name: review
  if: (type IN (pull_request)) AND (NOT head_branch = master)
- name: deploy
  if: (NOT type IN (pull_request)) AND (branch = master)

before_script:
  - yarn install

jobs:
  include:
  - stage: test
    script: yarn test
  - stage: review
    script:
      npm install -g exp;
      exp login -u $EXP_USERNAME -p $EXP_PASSWORD;
      echo "${TRAVIS_PULL_REQUEST_BRANCH//\//-}";
      exp publish --release-channel ${TRAVIS_PULL_REQUEST_BRANCH//\//-} --send-to $EXP_NOTIFICATION;
  - stage: deploy
    script:
      npm install -g exp;
      exp login -u $EXP_USERNAME -p $EXP_PASSWORD;
      exp publish;

notifications:
  email: false

branches:
  only:
  - master